### ISSUE TITLE
Is it possible that this library will be migrated to Jetbrains compose

### ISSUE THREAD

**Issue by ZXHHYJ** [olshevski/compose-navigation-reimagined#21]
rt

**Comment by ZXHHYJ** [comment]
Thank you for your answer.

**Comment by xiaozhikang0916** [comment]
Sorry for commenting in a closed issue, but I really need a navigation lib for KMM project.

Since all the androidX libs like lifecycle and viewmodel are not available in KMM, is it possible to extract a androidx-free module in KMM common layer, only with the ability of switching between Composable functions.

And then introduce androidx libs in android platform specific module to provide any other abilities like retrieve ViewModelStoreOwner by entry.

**Comment by ZXHHYJ** [comment]
你可以看看这个，不出意外是你想要的。https://github.com/adrielcafe/voyager
