### ISSUE TITLE
How to intercept navigation, such as the target page requiring login to access

### ISSUE THREAD

**Issue by Kuki93** [olshevski/compose-navigation-reimagined#37]

**Comment by olshevski** [comment]
@Kuki93 Not sure if I understand the case. If a user is not logged in, navigate to the login screen instead of going to the target page. It's your business logic that controls the navigation, so you can check the login state before doing the navigation. No need to intercept anything.
Can you please provide more details about your use-case?

**Comment by Kuki93** [comment]
thanks, I have already solved the problem。
